ALTER TABLE admins PACK_KEYS=1;
ALTER TABLE adverts PACK_KEYS=1;
ALTER TABLE bantype MODIFY channel VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE bantype DROP KEY key1;
ALTER TABLE bantype ADD KEY key1(channel, ident);
ALTER TABLE bantype PACK_KEYS=1;
ALTER TABLE banvars PACK_KEYS=1;
ALTER TABLE channels PACK_KEYS=1;
ALTER TABLE conf PACK_KEYS=1;
ALTER TABLE floodvars PACK_KEYS=1;
ALTER TABLE hostmasks PACK_KEYS=1;
ALTER TABLE kickreasons PACK_KEYS=1;
ALTER TABLE nickbks PACK_KEYS=1;
ALTER TABLE output PACK_KEYS=1;
ALTER TABLE passwords PACK_KEYS=1;
ALTER TABLE permbans PACK_KEYS=1;
ALTER TABLE raw PACK_KEYS=1;
ALTER TABLE servers PACK_KEYS=1;
ALTER TABLE timestamps PACK_KEYS=1;
ALTER TABLE topics PACK_KEYS=1;
ALTER TABLE trusted PACK_KEYS=1;
ALTER TABLE users PACK_KEYS=1;
ALTER TABLE wordbks PACK_KEYS=1;
CREATE TABLE services (
  host varchar(64) NOT NULL default '',
  ident varchar(64) NOT NULL default '',
  KEY key1(host,ident)
) TYPE=MyISAM PACK_KEYS=1;
