ALTER TABLE admins DROP INDEX key1;
ALTER TABLE admins ADD PRIMARY KEY (handle,ident);
ALTER TABLE adverts CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE bantype DROP INDEX key1;
ALTER TABLE bantype ADD PRIMARY KEY (channel,ident);
ALTER TABLE bantype CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE banvars DROP INDEX key1;
ALTER TABLE banvars ADD PRIMARY KEY (channel,ident);
ALTER TABLE banvars CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE channels DROP INDEX key1;
ALTER TABLE channels ADD PRIMARY KEY (name,ident);
ALTER TABLE channels CHANGE name name VARCHAR(50) NOT NULL;
ALTER TABLE conf DROP INDEX key1;
ALTER TABLE conf CHANGE prefix prefix VARCHAR(32);
ALTER TABLE conf ADD PRIMARY KEY (ident);
ALTER TABLE conf CHANGE nick nick VARCHAR(15) NOT NULL;
ALTER TABLE conf CHANGE altnick altnick VARCHAR(15) NOT NULL;
ALTER TABLE conf CHANGE user user VARCHAR(16) DEFAULT '';
ALTER TABLE conf CHANGE vhost vhost VARCHAR(63) DEFAULT '';
ALTER TABLE floodvars DROP INDEX key1;
ALTER TABLE floodvars ADD PRIMARY KEY (channel,ident);
ALTER TABLE floodvars CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE hostmasks DROP INDEX key1;
ALTER TABLE hostmasks ADD PRIMARY KEY (hostmask,channel,type,handle,ident);
ALTER TABLE hostmasks CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE hostmasks CHANGE hostmask hostmask VARCHAR(80) NOT NULL;
ALTER TABLE nickbks DROP INDEX key1;
ALTER TABLE nickbks ADD PRIMARY KEY (channel,pattern,ident);
ALTER TABLE nickbks CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE passwords DROP INDEX key1;
ALTER TABLE passwords ADD PRIMARY KEY (handle,channel,type,ident);
ALTER TABLE passwords CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE permbans DROP INDEX key1;
ALTER TABLE permbans ADD PRIMARY KEY (channel,mask,ident);
ALTER TABLE permbans CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE servers DROP INDEX key1;
ALTER TABLE servers ADD PRIMARY KEY (hostname,port,servermodes,pingfreq,protopers,linenoise,ident);
ALTER TABLE servers ADD id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT, ADD INDEX (id);
ALTER TABLE servers CHANGE hostname hostname VARCHAR(63) NOT NULL;
ALTER TABLE services DROP INDEX key1;
ALTER TABLE services ADD PRIMARY KEY (host,ident);
ALTER TABLE services CHANGE host host VARCHAR(63) NOT NULL;
ALTER TABLE timestamps DROP INDEX key1;
ALTER TABLE timestamps ADD PRIMARY KEY (ttype,tchannel,ident);
ALTER TABLE timestamps CHANGE tchannel tchannel VARCHAR(50) NOT NULL;
ALTER TABLE topics DROP INDEX key1;
ALTER TABLE topics ADD PRIMARY KEY (channel,pos,ident);
ALTER TABLE topics CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE trusted DROP INDEX key1;
ALTER TABLE trusted ADD PRIMARY KEY (host,ident);
ALTER TABLE trusted CHANGE host host VARCHAR(63) NOT NULL;
ALTER TABLE users DROP INDEX key1;
ALTER TABLE users ADD PRIMARY KEY (handle,channel,ident);
ALTER TABLE users CHANGE channel channel VARCHAR(50) NOT NULL;
ALTER TABLE wordbks DROP INDEX key1;
ALTER TABLE wordbks ADD PRIMARY KEY (channel,pattern,ident);
ALTER TABLE wordbks CHANGE channel channel VARCHAR(50) NOT NULL;

